2025-02-18 15:52:26,607 INFO: YRN startup [in /workspaces/FacialBlog/app/__init__.py:72]
2025-02-18 15:52:39,602 ERROR: Exception on /login [GET] [in /workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/FacialBlog/app/routes.py", line 58, in login
    return render_template('login.html', title=_('Login'), form=form)
                                               ^^^^^^^^^^
  File "/workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask_babel/__init__.py", line 756, in gettext
    return get_domain().gettext(*args, **kwargs)
           ^^^^^^^^^^^^
  File "/workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask_babel/__init__.py", line 750, in get_domain
    ctx.babel_domain = get_babel().instance.domain_instance
                       ^^^^^^^^^^^
  File "/workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask_babel/__init__.py", line 46, in get_babel
    return app.extensions['babel']
           ~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'babel'
2025-02-18 15:54:52,968 INFO: YRN startup [in /workspaces/FacialBlog/app/__init__.py:72]
2025-02-18 15:54:57,518 ERROR: Exception on /login [GET] [in /workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/FacialBlog/app/routes.py", line 58, in login
    return render_template('login.html', title=_('Login'), form=form)
                                               ^^^^^^^^^^
  File "/workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask_babel/__init__.py", line 756, in gettext
    return get_domain().gettext(*args, **kwargs)
           ^^^^^^^^^^^^
  File "/workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask_babel/__init__.py", line 750, in get_domain
    ctx.babel_domain = get_babel().instance.domain_instance
                       ^^^^^^^^^^^
  File "/workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask_babel/__init__.py", line 46, in get_babel
    return app.extensions['babel']
           ~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'babel'
2025-02-18 15:57:44,534 INFO: YRN startup [in /workspaces/FacialBlog/app/__init__.py:74]
2025-02-18 15:57:49,534 ERROR: Exception on /login [GET] [in /workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/FacialBlog/app/routes.py", line 58, in login
    return render_template('login.html', title=_('Login'), form=form)
                                               ^^^^^^^^^^
  File "/workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask_babel/__init__.py", line 756, in gettext
    return get_domain().gettext(*args, **kwargs)
           ^^^^^^^^^^^^
  File "/workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask_babel/__init__.py", line 750, in get_domain
    ctx.babel_domain = get_babel().instance.domain_instance
                       ^^^^^^^^^^^
  File "/workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask_babel/__init__.py", line 46, in get_babel
    return app.extensions['babel']
           ~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'babel'
2025-02-18 15:58:10,214 INFO: YRN startup [in /workspaces/FacialBlog/app/__init__.py:74]
2025-02-18 15:58:13,356 ERROR: Exception on /login [GET] [in /workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/FacialBlog/app/routes.py", line 58, in login
    return render_template('login.html', title=_('Login'), form=form)
                                               ^^^^^^^^^^
  File "/workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask_babel/__init__.py", line 756, in gettext
    return get_domain().gettext(*args, **kwargs)
           ^^^^^^^^^^^^
  File "/workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask_babel/__init__.py", line 750, in get_domain
    ctx.babel_domain = get_babel().instance.domain_instance
                       ^^^^^^^^^^^
  File "/workspaces/FacialBlog/venv/lib/python3.12/site-packages/flask_babel/__init__.py", line 46, in get_babel
    return app.extensions['babel']
           ~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'babel'
2025-02-18 15:58:53,356 INFO: YRN startup [in /workspaces/FacialBlog/app/__init__.py:75]
